function out = foo(xeval, yeval, varargin)

s = struct...
    ( 'x', -10:2:10 ...
    , 'y', (-10:2:10)' ...
    , 'semimajor', 0.2 ...
    , 'lambda', 0.4 ...
    , varargin{:} ...
    );

out = gabor(xeval, yeval, s)*255 + 127.5;
