function this = testFromBytes(varargin)

    persistent init__;
    this = inherit...
        ( TestCase()...
        , BaseBytesTest()...
        , autoobject(varargin{:})...
        );
    
    function check(format, data, bytes, varargin)
        %assertEquals asserts data types too; we just want to assert data
        assertIsEqual ...
            ( data ...
            , frombytes(bytes, format, varargin{:}) ...
            );
    end

end