function CauchyDemo(varargin)
    params = struct...
        ( 'edfname',    '' ...
        , 'dummy',      1  ...
        , 'skipFrames', 1  ...
        , 'requireCalibration', 0 ...
        , 'hideCursor', 0 ...
        , 'aviout', '' ...
        );
    
    params = namedargs(localExperimentParams(), params, varargin{:});
    
    require(getScreen(params), @runDemo);
    function runDemo(params)
        
        cauchy = CauchyDrawer('visible', 1);

        keyboardInput = KeyboardInput();
        
        stopKey = KeyDown();
       
        main = mainLoop ...
            ( 'graphics', {cauchy} ...
            , 'triggers', {stopKey} ...
            , 'input', {keyboardInput} ...
            );
        
        stopKey.set(main.stop, 'q');
        
        params = require(initparams(params), keyboardInput.init, main.go);
    end
end
