function this = CircleDemo(varargin)

    radius = 5;
    wavelength = 0.9;
    tfreq = 10;

    %we're going to show a ring with a second order motion going around
    %the outside of it...

    clambda = wavelength;

    gratingParams = structcbind ...
        ( struct ... % the flicker
          ( 'lobes', round(radius * 2 * pi ./ clambda) ...
          , 'omega', [tfreq -tfreq] * 2 * pi ...
          , 'radius', radius ...
          , 'width', 1 ...
          , 'color', [1 1 1]'/6 ...
          , 'loc', [0 0]' ...
          ) ...
        , struct ... %the borders
          ( 'lobes', 0 ...
          , 'omega', 0 ...
          , 'radius', radius + [1 -1]/2 .* 1.5 ...
          , 'width', 0.1 ...
          , 'color', [1 1 1]' / 16 ...
          ) ...
        );
    grating = SimpleCircularGratingSource(gratingParams);

    flanker_radii = [8];
    n = 6; %number of flankers

    %actually, dt is determined by step size...
    dt = 1./tfreq .* 1/2;
    dcphase = 1/2; % -1/2, 3/2, etc
    dphase = dcphase .* wavelength ./ flanker_radii;

    leftward = 0.150;
    rightward = 0.100;

    spotParams = structcbind ...
        ( struct ...
          ( 'radius', flanker_radii ...
          , 't', 0 ...
          , 'dt', 0.1 ...
          , 'x', 0 ...
          , 'y', 0 ...
          , 'dphase', dphase ...
          , 'wavelength', wavelength * flanker_radii / radius ...
          , 'velocity', wavelength * flanker_radii / radius * tfreq ...
          , 'width', 1 ...
          , 'duration', dt*2 ...
          ) ...
        );

    counterphase = struct...
        ( 'velocity', [-1 1] ...
        , 'color', [1;1;1]*[leftward rightward] ...
        );

    distribution = struct ...
        ( 'phase', (0:(n-1)).* 2.*pi/n ...
        , 'angle', 90 + (0:n-1) * 360/n ...
        );

    % have two motion processes, and start/stop them on a timer...?
    motionParams = cellreduce ...
        ( @expand_struct_grid, spotParams ...
        , {counterphase, distribution} ...
        );

    motion = CircularCauchyMotion(motionParams);

    fixation = FilledDisk([0;0], 0.1, 'visible', 1);

    kb_ = KeyDown();
    t_ = Trigger();
    drawer1_ = CauchySpritePlayer('process', motion);
    drawer2_ = CircularGratingDrawer('source', grating);

    persistent init__;
    this = autoobject();

    function params = run(params)
        main = mainLoop...
            ( 'input', {params.input.keyboard} ...
            , 'graphics', {fixation, drawer2_, drawer1_} ...
            , 'triggers', {kb_, t_} ...
            );

        kb_.set(main.stop, 'ESCAPE');
        kb_.set(@switchEnvelope, 'e');
        kb_.set(@switchCarrier, 'c');
        t_.singleshot(always(), @start);
        %        t_.multishot(function(x) x.get())

        params = main.go(params);
    end

    function k = start(k)
        drawer1_.setVisible(1, k.next);
        drawer2_.setVisible(1, k.next);
        fixation.setVisible(1, k.next);
    end

    function x = switchEnvelope(k)
        motion.setDphase(-motion.getDphase());
    end

    function x = switchCarrier(k)
        motion.setColor( ...
            reshape(flipdim(reshape(motion.getColor(), 3, 2, []), 2), 3, []));
    end

    %    playDemo(this, 'skipFrames', 0, varargin{:});
    playDemo(this, varargin{:});
end
