function this = demo1(varargin)

e = ApparentVelocityCompensation( ...
      'trialParams.timeDilation', 1 ...
    , 'trialParams.goodTrialTones', [] ...
    , 'trialParams.badTrialTones', [] ...
    , 'trialParams.badTrialTimeout', 0 ...
    , 'trialParams.fixationSettlingTime', 0 ...
    , 'trialParams.nAveragingSamples', 1 ...
    , 'trialParams.fineFixationTime', 0 ...
    , 'cueWindow', [0 0] ...
    , 'edfname', '' ...
    , 'logfile', '' ...
    , 'subject', 'zzz' ...
    , 'filename', '' ...
    , 'numLeft', Inf ...
    , varargin{:} ...
);