function mkmovies()
    c = Calibration('screenNumber',  2, 'interval', 1/60);
    
    a = ApparentMotion ...
        ( 'dx', 0.5 ...
        , 'dt', 1/30 ...
        , 'n', 30 ...
        , 'primitive', CauchyPatch...
            ( 'size', [0.5 1 0.5] ...
            , 'center', [-5 0 0] ...
            , 'velocity', 0 ...
            ) ...
        );
    m1 = movie(a, c) / 2;
    m1 = cat(3, m1, flipdim(m1, 3));
    m2avi(m1, 'global.avi', c);
    
    a = ApparentMotion ...
        ( 'dx', 1/6 ...
        , 'dt', 1/60 ...
        , 'n', 60 ...
        , 'primitive', Bar...
            ( 'size', [0.2 1 1/60] ...
            , 'center', [-5 0 0] ...
            ) ...
        );
        
    m1 = movie(a, c);
    m1 = cat(3, m1, flipdim(m1, 3));
    m2avi(m1, 'smooth_bar.avi', c);
    
    a = ApparentMotion ...
        ( 'dx', 1 ...
        , 'dt', 1/10 ...
        , 'n', 10 ...
        , 'primitive', Bar...
            ( 'size', [0.2 1 1/10] ...
            , 'center', [-5 0 0] ...
            ) ...
        );
    
    m1 = movie(a, c);
    m1 = cat(3, m1, flipdim(m1, 3));
    m2avi(m1, 'apparent_bar.avi', c);
    
    a = ApparentMotion ...
        ( 'dx', 1/6 ...
        , 'dt', 1/60 ...
        , 'n', 60 ...
        , 'primitive', CauchyPatch...
            ( 'size', [1 1 1/120] ...
            , 'center', [-5 0 0] ...
            ) ...
        );
        
    m1 = movie(a, c);
    m1 = cat(3, m1, flipdim(m1, 3));
    m2avi(m1, 'smooth_bar.avi', c);
    
end