function grid = expandGrid(varargin)
    sizes = cellfun('prodofsize', varargin);
    indices = fullfact(sizes);
    grid = cellfun...
        ( @(row)arrayfun...
            ( @(x,y)x{1}(y) ...
            , varargin...
            , row ...
            , 'UniformOutput', 0) ...
        , num2cell(indices, 2)...
        , 'UniformOutput', 0);
    grid = cat(1, grid{:});
end